### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by caixiaoshun** [coffeelize/QHUMaster#1]
在overleaf中不能编译成功呀
![image](https://github.com/user-attachments/assets/1cc1f91e-e681-4db5-bd0a-78e912a5cc8a)

**Comment by coffeelize** [comment]
我之前在overleaf中编译成功的，稍后我看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月19日(周四) 中午11:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [coffeelize/QHUMaster] 编译失败 (Issue #1)




 
在overleaf中不能编译成功呀
 image.png (view on web)

**Comment by caixiaoshun** [comment]
你好，我找到原因了，需要将编译器改为xelatex即可编译成功：
![image](https://github.com/user-attachments/assets/9f1c6bc1-d7d1-43db-8a25-23c9dce4f2c1)

**Comment by coffeelize** [comment]
OKOK，很高兴模板能帮助到你，不过青大基本上没几个人在用LaTeX，加上自己已经毕业，我也就没有开发和维护的动力了。
你要用的话还是请慎重考虑，可能部分格式和Word模板中的格式还是有出入。另外，GPT处理LaTeX问题会非常有帮助，遇到代码编译报错了可以问问它
---- 回复的原邮件 ----
***@***.***>发送日期2024年12月19日 ***@***.***>***@***.***>,
***@***.***>主题Re: [coffeelize/QHUMaster] 编译失败 (Issue #1)
你好，我找到原因了，需要将编译器改为xelatex即可编译成功：
image.png (view on web)
